name: moving_sprite
description: A basic example where a sprite moves around in a 2D pane.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0-releasecandidate.16
  flame_forge2d: ^0.8.2-releasecandidate.15

  cupertino_icons: ^1.0.2
  forge2d: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
